version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/projects/standard-projects/issue-tracker-mini"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/projects/standard-projects/personal-finance-dashboard"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/projects/macro-projects/helpdesk-ticket-system"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/projects/macro-projects/hotel-booking-system"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/projects/macro-projects/task-management-platform"
    schedule:
      interval: "weekly"
