spring.application.name=hotel-booking-system

# Base H2 embarquee en fichier (persistante entre redemarrages)
spring.datasource.url=jdbc:h2:file:./data/hotel-booking-db;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=8081
