server:
  port: 8082

spring:
  application:
    name: notesapp-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/notesapp}
    username: ${SPRING_DATASOURCE_USERNAME:notesapp}
    password: ${SPRING_DATASOURCE_PASSWORD:notesapp}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.format_sql: false
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: notesapp-backend
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.jihedapps.notesapp.*"
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8090/realms/notesapp/protocol/openid-connect/certs}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8762/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

minio:
  url: ${MINIO_URL:http://localhost:9100}
  access-key: ${MINIO_ACCESS_KEY:notesapp}
  secret-key: ${MINIO_SECRET_KEY:notesapp123}
  bucket: ${MINIO_BUCKET:notesapp-attachments}

notesapp:
  kafka:
    topic-note-events: note-events
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4300}

management:
  endpoints:
    web:
      exposure:
        include: health,info
